{
 "title": "Demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Attendence",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mosip",
     "rawSql": "SELECT SUM(total), SUM(presented) FROM mosip.attendence LIMIT 50 "
    }
   ]
  },
  {
   "title": "Registration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mosip",
     "rawSql": "SELECT suceed FROM mosip.registration LIMIT 50 "
    }
   ]
  },
  {
   "title": "Accessed",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "mosip",
     "rawSql": "SELECT accessed, index_no FROM mosip.access LIMIT 50 "
    }
   ]
  },
  {
   "title": "Booked Resources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mosip",
     "rawSql": "SELECT available, booked FROM mosip.resorces ORDER BY available LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 17 },
   "targets": [
    {
     "dataset": "mosip",
     "rawSql": "SELECT name, percentage FROM mosip.metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "mosip",
     "rawSql": "SELECT detail FROM mosip.logs LIMIT 50 "
    }
   ]
  }
 ]
}